//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebOlx2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lot
    {
        public int LotID { get; set; }
        public System.DateTime Date { get; set; }
        public int CatId { get; set; }
        public int Price { get; set; }
        public string Title { get; set; }
        public string Desc { get; set; }
        public string UserName { get; set; }
    }
}
